### ISSUE TITLE
Is this being used in production?

### ISSUE THREAD

**Issue by philipbjorge** [Agrando/IdentityServer.Contrib.RavenDB#1]
Curious to know if this is being used in any production settings yet?

**Comment by bjarteskogoy** [comment]
Not yet. I wrote this to try out hosting IdentityServer on multiple geographic locations with "shared" storage, RavenDB with replication.

**Comment by bjarteskogoy** [comment]
We've started using this in production for client credentials now.

**Comment by bjarteskogoy** [comment]
We've been using this in production for a while now. No issues yet. We're hosting it in Azure on two different locations, with RavenDB set up to replicate between the two locations.
