### ISSUE TITLE
IdentityServer4 support

### ISSUE THREAD

**Issue by lahma** [Agrando/IdentityServer.Contrib.RavenDB#4]
I found your project while trying to find a RavenDB compatible store for IdentityServer4. I forked the repo and tried to do quick port but it seems that the task is a bit more complicated than that with APIs and stores being different. It might be even hard to maintain backwards compatibility with JSON schema.

Should this project create a new repo `IdentityServer4.Contrib.RavenDB` and create a new revisited implementation or are you more on maintenance mode with this? I could also create such new repo and publish on NuGet, but I don't want to step on anyone's toes. This repository also doesn't define a license file so that is currently a blocker for that idea (would be good to have one anyway).

What are your thoughts?

**Comment by bjarteskogoy** [comment]
I no longer work at the company. But I'm still a member of the organisation on Github.
The lack of a license can be seen as the most permissive license you can find.

A new repo for IdentityServer4 would be the right thing. And maybe also support for RavenDB 4. There is a branch in the repo where I started out on RavenDB 4 support.

Feel free to create a new repo and publish it to NuGet.

**Comment by bjarteskogoy** [comment]
Getting a proper build pipeline with testing up and running would be a massive improvement too.

**Comment by lahma** [comment]
Thank you for getting back so promptly. I'll see what I can do as part of our Identity IdentityServer4 migration 👍🏻

**Comment by lahma** [comment]
And just found about https://github.com/ravendb/IdentityServer4.Contrib.RavenDB , so this might be the easiest path as it's coming straight from the source. Thanks again for guidance and information!
